#!/usr/bin/env bash

# Process:
# Load up 24 x 10000 objects
# Wait 2 minutes
# Delete all objects
# Wait 2 minutes
# Re-insert objects
# Check objects

if ! hash realpath 2>/dev/null
then
  echo "'realpath' cmd missing" 1>&2
  exit 1
fi
source_dir="$(dirname $(realpath $0))"
source "$source_dir/common.bash"

nuke_all_objects

