#!/usr/bin/env bash

# Process:
# Load up 24 x 10000 objects
# Wait 2 minutes
# Delete all objects
# Wait 2 minutes
# Re-insert objects
# Check objects

if ! hash realpath 2>/dev/null
then
  echo "'realpath' cmd missing" 1>&2
  exit 1
fi
source_dir="$(dirname $(realpath $0))"
source "$source_dir/common.bash"

function object_deleter
{
  local -i deleter_id=$1
  pinfo "starting deleter with id: $deleter_id"

  local -i j=0
  for ((j=0; j < object_count; ++j))
  do
    local host="$(curl_host)"
    curl_exec 'object_deleter' -XDELETE "$host/buckets/bucket-$deleter_id/keys/$j"
  done

  pinfo "done - deleter with id: $deleter_id"
}

declare -i i=0

for ((i=0; i < num_procs; ++i))
do
  object_deleter $i &
done

wait

pinfo 'cleanup done'

