#!/usr/bin/env bash

# Process:
# Load up 24 x 10000 objects
# Wait 2 minutes
# Delete all objects
# Wait 2 minutes
# Re-insert objects
# Check objects

if ! hash realpath 2>/dev/null
then
  echo "'realpath' cmd missing" 1>&2
  exit 1
fi
source_dir="$(dirname $(realpath $0))"
source "$source_dir/common.bash"

test_object='tester.obj'

dd if=/dev/urandom bs=65536 count=1 2>/dev/null | openssl enc -a > $test_object

function object_loader
{
  local -i loader_id=$1
  pinfo "starting loader with id: $loader_id"

  local -i j=0
  for ((j=0; j < object_count; ++j))
  do
    local host="$(curl_host)"
    curl_exec 'object_loader' -H'Content-Type: text/plain' -XPUT "$host/buckets/bucket-$loader_id/keys/$j" --data-binary "@$test_object"
    # curl_exec 'object_loader' -H'Content-Type: text/plain' -XPUT "$host/buckets/bucket-$loader_id/keys/$j" -d "OBJECT $j"
  done

  pinfo "done - loader with id: $loader_id"
}

function object_checker
{
  local -i checker_id=$1
  pinfo "starting checker with id: $checker_id"

  local -i j=0
  for ((j=0; j < object_count; ++j))
  do
    local host="$(curl_host)"
    curl_exec 'object_checker' -XGET "$host/buckets/bucket-$checker_id/keys/$j"
  done

  pinfo "done - checker with id: $checker_id"
}

function object_deleter
{
  local -i deleter_id=$1
  pinfo "starting deleter with id: $deleter_id"

  local -i j=0
  for ((j=0; j < object_count; ++j))
  do
    local host="$(curl_host)"
    # PW curl_exec 'object_deleter' -XDELETE "$host/buckets/bucket-$deleter_id/keys/$j?pw=3"
    # NO PW curl_exec 'object_deleter' -XDELETE "$host/buckets/bucket-$deleter_id/keys/$j"
    curl_exec 'object_deleter' -XDELETE "$host/buckets/bucket-$deleter_id/keys/$j?pw=3"
  done

  pinfo "done - deleter with id: $deleter_id"
}

nuke_all_objects
sleep $sleep_seconds

declare -i i=0

for ((i=0; i < num_procs; ++i))
do
  object_loader $i &
done

wait
pinfo 'initial load done'
sleep $sleep_seconds

while true
do
  for ((i=0; i < num_procs; ++i))
  do
    object_deleter $i &
  done

  wait
  pinfo 'object delete done'
  sleep $sleep_seconds

  for ((i=0; i < num_procs; ++i))
  do
    object_loader $i &
  done

  wait
  pinfo 'object load done'

  for ((i=0; i < num_procs; ++i))
  do
    object_checker $i &
  done

  wait
  pinfo 'object check done'
done

